spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_extra?
      useSSL=false&
      allowPublicKeyRetrieval=true&
      serverTimezone=Asia%2FSeoul&
      characterEncoding=UTF-8&
      cachePrepStmts=true&
      useServerPrepStmts=true&
      rewriteBatchedStatements=true
    username: root
    password: tjehwo0116
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 200            # 변경: 배치 크기 설정
        order_inserts: true          # 변경: 연관 INSERT 순서 자동 정렬
        order_updates: true          # 변경: 연관 UPDATE 순서 자동 정렬

springdoc:
  swagger-ui:
    path: /docs/swagger
